name: engineering-smart-cities
channels:
  - conda-forge
dependencies:
  - appnope=0.1.3
  - asttokens=2.1.0
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=22.10.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - debugpy=1.6.3
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - importlib-metadata=5.0.0
  - importlib_resources=5.10.0
  - ipykernel=6.17.1
  - ipython=8.6.0
  - ipywidgets=8.0.2
  - jedi=0.18.1
  - jsonschema=4.17.0
  - jupyter_client=7.4.7
  - jupyter_core=5.0.0
  - jupyterlab_widgets=3.0.3
  - libblas=3.9.0
  - libcblas=3.9.0
  # - libcxx=14.0.6
  - libffi=3.4.2
  # - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - llvm-openmp=15.0.5
  - matplotlib-inline=0.1.6
  - mypy=0.991
  - mypy_extensions=0.4.3
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - numpy=1.23.5
  - openssl=3.0.7
  - packaging=21.3
  - pandas=1.5.1
  - parso=0.8.3
  - pathspec=0.10.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.32
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.13.0
  - pyparsing=3.0.9
  - pyrsistent=0.19.2
  - python=3.10.7
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytz=2022.6
  - pyzmq=24.0.1
  - readline=8.1.2
  - setuptools=65.5.1
  - six=1.16.0
  - stack_data=0.6.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.5.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - wcwidth=0.2.5
  - wheel=0.38.4
  - widgetsnbextension=4.0.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.10.0
  - pip:
    # - absl-py==1.3.0
    # - aiosignal==1.3.1
    # - ale-py==0.7.5
    # - atari-py==0.2.9
    # - autorom==0.4.2
    # - autorom-accept-rom-license==0.4.2
    # - cachetools==5.2.0
    # - certifi==2022.9.24
    # - charset-normalizer==2.1.1
    # - click==8.0.4
    # - cloudpickle==2.2.0
    # - contourpy==1.0.6
    # - cycler==0.11.0
    # - distlib==0.3.6
    - dm-tree==0.1.7
    - epyt==1.0.1
    # - filelock==3.8.0
    # - fonttools==4.38.0
    # - frozenlist==1.3.3
    # - google-auth==2.14.1
    # - google-auth-oauthlib==0.4.6
    # - grpcio==1.50.0
    - gym==0.23.1
    # - gym-notices==0.0.8
    # - idna==3.4
    - imageio==2.22.4
    # - kiwisolver==1.4.4
    - lz4==4.0.2
    # - markdown==3.4.1
    # - markupsafe==2.1.1
    # - matplotlib==3.6.2
    # - msgpack==1.0.4
    - networkx==2.8.8
    # - oauthlib==3.2.2
    - pillow==9.3.0
    # - protobuf==3.20.1
    # - pyasn1==0.4.8
    # - pyasn1-modules==0.2.8
    # - pygame==2.1.2
    - pywavelets==1.4.1
    # - pyyaml==6.0
    - ray==2.1.0
    # - requests==2.28.1
    # - requests-oauthlib==1.3.1
    # - rsa==4.9
    - scikit-image==0.19.3
    - scipy==1.9.3
    - tabulate==0.9.0
    - tensorboard==2.11.0
    # - tensorboard-data-server==0.6.1
    # - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tifffile==2022.10.10
    - torch==1.13.0
    # - tqdm==4.64.1
    # - urllib3==1.26.12
    # - virtualenv==20.16.7
    # - werkzeug==2.2.2
